/*
 *
 * UserSignIn constants
 *
 */

export const DEFAULT_ACTION = 'app/UserSignIn/DEFAULT_ACTION';
export const USER = {
  SIGNIN: `USER.SIGNIN`,
  SIGNIN_SUCCESS: `USER.SIGNIN_SUCCESS`,
  SIGNIN_FAILED: `USER.SIGNIN_FAILED`,
  FORM_DATA_CAHANGED: `USER.FORM_DATA_CAHANGED`,
  CANCEL_ERROR: `USER.CANCEL_ERROR`
}
