/*
 *
 * SigninPage constants
 *
 */

export const DEFAULT_ACTION = 'app/SigninPage/DEFAULT_ACTION';

export const SIGNIN = {
  USERNAME_CHANGE: 'SIGNIN.USERNAME_CHANGE',
  PASSWORD_CHANGE: 'SIGNIN.PASSWORD_CHANGE',
  SIGNIN_REQ: 'SIGNIN.SIGNIN_REQ',
  SIGNIN_SUCCESS: 'SIGNIN.SIGNIN_SUCCESS',
  SIGNIN_FAILED: 'SIGNIN.SIGNIN_FAILED'
};
