/*
 *
 * SerialsPage constants
 *
 */

export const DEFAULT_ACTION = 'app/SerialsPage/DEFAULT_ACTION';
export const SERIALS = {
  FETCHING:`SERIALS.FETCHING`,
  FETCHING_SUCCESS:`SERIALS.FETCHING_SUCCESS`,
  FETCHING_FAILED:`SERIALS.FETCHING_FAILED`,

  ON_CREATE_NEW_FORM_DATA_CHANGED:`SERIALS.ON_CREATE_NEW_FORM_DATA_CHANGED`,

  CREATE_NEW_SERIALS:`SERIALS.CREATE_NEW_SERIALS`,
  UPDATE_SERIAL_DATA_CHANGED: `SERIALS.UPDATE_SERIAL_DATA_CHANGED`,
  SELECT_SERIAL: `SERIALS.SELECT_SERIAL`,
  UPDATE_SERIAL: `SERIALS.UPDATE_SERIAL`,
  DELETE_SERIAL: `SERIALS.DELETE_SERIAL`,
  ADD_NEW_SERIALS_FORM_DATA_CHANGED: `SERIALS.ADD_NEW_SERIALS_FORM_DATA_CHANGED`,
  ADD_NEW_SERIALS: `SERIALS.ADD_NEW_SERIALS`,
}
