/*
 *
 * MainPage constants
 *
 */

export const DEFAULT_ACTION = 'app/MainPage/DEFAULT_ACTION';
export const NETWORKS = {
  FETCHING: 'NETWORKS.FETCHING',
  FETCHING_FAILED: 'NETWORKS.FETCHING_FAILED',
  FETCHING_SUCCESS: 'NETWORKS.FETCHING_SUCCESS',
  ADD_NETWORK: 'NETWORKS.ADD_NETWORK',
  DELETE_NETWORK: 'NETWORKS.DELETE_NETWORK',

  NETWORK_FORM_CHANGED: 'NETWORKS.NETWORK_FORM_CHANGED',
}
