/*
 *
 * MikrotikUserPage constants
 *
 */

export const DEFAULT_ACTION = 'app/MikrotikUserPage/DEFAULT_ACTION';
export const SERIALS = {
  CHARGE_SERIAL: `SERIALS.CHARGE_SERIAL`,
  SET_SERIAL: `SERIALS.SET_SERIAL`,
  CHARGEED_SUCCESSFULL: `SERIALS.CHARGEED_SUCCESSFULL`,
  ERROR: `SERIALS.ERROR`,
  REMOVE_CHARGED_SUCCESS: `SERIALS.REMOVE_CHARGED_SUCCESS`,
  REMOVE_ERROR: `SERIALS.REMOVE_ERROR`
}
export const PROFILES = {
  FETCH: `PROFILES.FETCH`,
  FETCH_SUCCESS: `PROFILES.FETCH_SUCCESS`,
  SET_PROFILE_TO_SUBSCRIBE: `PROFILES.SET_PROFILE_TO_SUBSCRIBE`,
  SUBSCRIBE: `PROFILES.SUBSCRIBE`,
  LOG_INTO_MIKROTIK: `PROFILES.LOG_INTO_MIKROTIK`,
}
