/*
 *
 * ProfilesContainer constants
 *
 */

export const DEFAULT_ACTION = {
  ADD_NEW_PROFILE_FORM_DATA_CAHNGED: `PROFILE.ADD_NEW_PROFILE_FORM_DATA_CAHNGED`,
  ADD_NEW_PROFILE: `PROFILE.ADD_NEW_PROFILE`,
  SELECT_PROFILE: `PROFILE.SELECT_PROFILE`,
  DELETE_PROFILE: `PROFILE.DELETE_PROFILE`,
};
