/*
 *
 * NetworkPage constants
 *
 */

export const DEFAULT_ACTION = 'app/NetworkPage/DEFAULT_ACTION';
export const MIKROTIK = {
  FETCH_ALL_USERS:`MIKROTIK.FETCH_ALL_USERS`,
  FETCH_ALL_USERS_SUCCESS:`MIKROTIK.FETCH_ALL_USERS_SUCCESS`,
  FETCH_ALL_USERS_FAILED:`MIKROTIK.FETCH_ALL_USERS_FAILED`,

  FETCH_ALL_PROFILES:`MIKROTIK.FETCH_ALL_PROFILES`,
  FETCH_ALL_PROFILES_SUCCESS:`MIKROTIK.FETCH_ALL_PROFILES_SUCCESS`,
  FETCH_ALL_PROFILES_FAILED:`MIKROTIK.FETCH_ALL_PROFILES_FAILED`,

  ADD_NEW_MIKROTIK_USER: `MIKROTIK.ADD_NEW_MIKROTIK_USER`,
  ADD_NEW_USER_FORM_DATA_CAHNGED: `MIKROTIK.ADD_NEW_USER_FORM_DATA_CAHNGED`
}
